api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    collection:
        pagination:
            enabled: false
            client_enabled: true
            client_items_per_page: true
            items_per_page: 50
            page_parameter_name: 'page'
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
    formats:
        json:
            mime_types: ['application/json']
    enable_swagger_ui: true
