# vichuploaderbundle Configuration
vich_uploader:
    db_driver: orm
    mappings:
        object_images:
            uri_prefix:         '%vich.path.object_images%'
            upload_destination: '%kernel.project_dir%/public/%vich.path.object_images%'
            namer:              vich_uploader.namer_uniqid